import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Navbar from "../components/AboutNav";
import AboutPages from "@/components/AboutPages";
import AboutBanner from "@/components/AboutBanner";
import Teams from "@/components/TeamSection";
import Footer from "@/components/FooterSection";

const AboutPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Company_Profile</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Navbar />
      <AboutBanner />
      <AboutPages />
      <Teams />
      <Footer />
      {/* <LandingPageTemplate /> */}
    </>
  );
};

export default AboutPage;
