import { NextPage } from "next";
import Head from "next/head";
// import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Navbar from "../components/Navbar";
import HeroSection from "../components/HeroSection";
import ServiceSection from "../components/ServiceSection";
import AboutUs from "../components/AboutUs";
import Testimonials from "@/components/TestimonialsSection";
import Teams from "@/components/TeamSection";
import Footer from "@/components/FooterSection";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Company_Profile</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Navbar />
      <HeroSection />
      <ServiceSection />
      <AboutUs />
      <Testimonials />
      <Teams />
      <Footer />
      {/* <LandingPageTemplate /> */}
    </>
  );
};

export default Index;
