import { NextPage } from "next";
import Head from "next/head";
// import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Navbar from "../components/ServiceNav";
import ServicesBanner from "../components/ServiceBanner";
import ServiceDetails from "../components/ServiceDetails";
import Testimonials from "@/components/TestimonialsSection";
import Footer from "@/components/FooterSection";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Company_Profile</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Navbar />
      <ServicesBanner />
      <ServiceDetails />
      <Testimonials />
      <Footer />
      {/* <LandingPageTemplate /> */}
    </>
  );
};

export default Index;
