import { NextPage } from "next";
import Head from "next/head";
// import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Navbar from "../components/TeamNav";
import TeamBanner from "../components/TeamBanner";
import DetailTeam from "../components/DetailTeam";
import Footer from "@/components/FooterSection";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Company_Profile</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Navbar />
      <TeamBanner />
      <DetailTeam />
      <Footer />
      {/* <LandingPageTemplate /> */}
    </>
  );
};

export default Index;
